### ISSUE TITLE
same icon in inventory

### ISSUE THREAD

**Issue by GeekinaCave** [mcilhargey/flowcontrolbobs#1]
Hi, there is a detail with the mod: the icons in the inventory are all the iron pipe icon. how can fix it?
Factorio 14.21

**Comment by Nagapito** [comment]
Line 114 of data-final-fixes, add:

new_pipes[value].recipe.icon = pic1..p[key]

**Comment by Nagapito** [comment]
Also, rename data-final-fixes.lua to data-updates.lua and the recipes will get the correct names and proper alignements!!

**Comment by mcilhargey** [comment]
This will be addressed
